#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_QUANLYNHANSU_2")]
	public partial class DB_QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBAOHIEM(tblBAOHIEM instance);
    partial void UpdatetblBAOHIEM(tblBAOHIEM instance);
    partial void DeletetblBAOHIEM(tblBAOHIEM instance);
    partial void InserttblTAIKHOAN(tblTAIKHOAN instance);
    partial void UpdatetblTAIKHOAN(tblTAIKHOAN instance);
    partial void DeletetblTAIKHOAN(tblTAIKHOAN instance);
    partial void InserttblCHAMCONG(tblCHAMCONG instance);
    partial void UpdatetblCHAMCONG(tblCHAMCONG instance);
    partial void DeletetblCHAMCONG(tblCHAMCONG instance);
    partial void InserttblCHITIETCHUCVU(tblCHITIETCHUCVU instance);
    partial void UpdatetblCHITIETCHUCVU(tblCHITIETCHUCVU instance);
    partial void DeletetblCHITIETCHUCVU(tblCHITIETCHUCVU instance);
    partial void InserttblCHUCVU(tblCHUCVU instance);
    partial void UpdatetblCHUCVU(tblCHUCVU instance);
    partial void DeletetblCHUCVU(tblCHUCVU instance);
    partial void InserttblHOPDONG(tblHOPDONG instance);
    partial void UpdatetblHOPDONG(tblHOPDONG instance);
    partial void DeletetblHOPDONG(tblHOPDONG instance);
    partial void InserttblKHENTHUONGKYLUAT(tblKHENTHUONGKYLUAT instance);
    partial void UpdatetblKHENTHUONGKYLUAT(tblKHENTHUONGKYLUAT instance);
    partial void DeletetblKHENTHUONGKYLUAT(tblKHENTHUONGKYLUAT instance);
    partial void InserttblLUONG(tblLUONG instance);
    partial void UpdatetblLUONG(tblLUONG instance);
    partial void DeletetblLUONG(tblLUONG instance);
    partial void InserttblNHANVIEN(tblNHANVIEN instance);
    partial void UpdatetblNHANVIEN(tblNHANVIEN instance);
    partial void DeletetblNHANVIEN(tblNHANVIEN instance);
    partial void InserttblPHONGBAN(tblPHONGBAN instance);
    partial void UpdatetblPHONGBAN(tblPHONGBAN instance);
    partial void DeletetblPHONGBAN(tblPHONGBAN instance);
    #endregion
		
		public DB_QLNSDataContext() : 
				base(global::QuanLyNhanSu.Properties.Settings.Default.DB_QUANLYNHANSU_2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBAOHIEM> tblBAOHIEMs
		{
			get
			{
				return this.GetTable<tblBAOHIEM>();
			}
		}
		
		public System.Data.Linq.Table<tblTAIKHOAN> tblTAIKHOANs
		{
			get
			{
				return this.GetTable<tblTAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<tblCHAMCONG> tblCHAMCONGs
		{
			get
			{
				return this.GetTable<tblCHAMCONG>();
			}
		}
		
		public System.Data.Linq.Table<tblCHITIETCHUCVU> tblCHITIETCHUCVUs
		{
			get
			{
				return this.GetTable<tblCHITIETCHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<tblCHUCVU> tblCHUCVUs
		{
			get
			{
				return this.GetTable<tblCHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<tblHOPDONG> tblHOPDONGs
		{
			get
			{
				return this.GetTable<tblHOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<tblKHENTHUONGKYLUAT> tblKHENTHUONGKYLUATs
		{
			get
			{
				return this.GetTable<tblKHENTHUONGKYLUAT>();
			}
		}
		
		public System.Data.Linq.Table<tblLUONG> tblLUONGs
		{
			get
			{
				return this.GetTable<tblLUONG>();
			}
		}
		
		public System.Data.Linq.Table<tblNHANVIEN> tblNHANVIENs
		{
			get
			{
				return this.GetTable<tblNHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tblPHONGBAN> tblPHONGBANs
		{
			get
			{
				return this.GetTable<tblPHONGBAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBAOHIEM")]
	public partial class tblBAOHIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _LoaiBaoHiem;
		
		private string _SoThe;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _NoiCap;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnLoaiBaoHiemChanging(string value);
    partial void OnLoaiBaoHiemChanged();
    partial void OnSoTheChanging(string value);
    partial void OnSoTheChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    #endregion
		
		public tblBAOHIEM()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBaoHiem", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LoaiBaoHiem
		{
			get
			{
				return this._LoaiBaoHiem;
			}
			set
			{
				if ((this._LoaiBaoHiem != value))
				{
					this.OnLoaiBaoHiemChanging(value);
					this.SendPropertyChanging();
					this._LoaiBaoHiem = value;
					this.SendPropertyChanged("LoaiBaoHiem");
					this.OnLoaiBaoHiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThe", DbType="VarChar(20)")]
		public string SoThe
		{
			get
			{
				return this._SoThe;
			}
			set
			{
				if ((this._SoThe != value))
				{
					this.OnSoTheChanging(value);
					this.SendPropertyChanging();
					this._SoThe = value;
					this.SendPropertyChanged("SoThe");
					this.OnSoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(50)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblBAOHIEM", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblBAOHIEMs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblBAOHIEMs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTAIKHOAN")]
	public partial class tblTAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Quyen;
		
		private int _MaNhanVien;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    #endregion
		
		public tblTAIKHOAN()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(20)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL")]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblTAIKHOAN", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblTAIKHOANs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblTAIKHOANs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCHAMCONG")]
	public partial class tblCHAMCONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private System.DateTime _NgayCham;
		
		private string _TrinhTrang;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnNgayChamChanging(System.DateTime value);
    partial void OnNgayChamChanged();
    partial void OnTrinhTrangChanging(string value);
    partial void OnTrinhTrangChanged();
    #endregion
		
		public tblCHAMCONG()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCham", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayCham
		{
			get
			{
				return this._NgayCham;
			}
			set
			{
				if ((this._NgayCham != value))
				{
					this.OnNgayChamChanging(value);
					this.SendPropertyChanging();
					this._NgayCham = value;
					this.SendPropertyChanged("NgayCham");
					this.OnNgayChamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhTrang", DbType="NVarChar(30)")]
		public string TrinhTrang
		{
			get
			{
				return this._TrinhTrang;
			}
			set
			{
				if ((this._TrinhTrang != value))
				{
					this.OnTrinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TrinhTrang = value;
					this.SendPropertyChanged("TrinhTrang");
					this.OnTrinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblCHAMCONG", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblCHAMCONGs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblCHAMCONGs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCHITIETCHUCVU")]
	public partial class tblCHITIETCHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private int _MaChucVu;
		
		private System.Nullable<decimal> _LuongCoBan;
		
		private System.Nullable<double> _PhuCapChucVu;
		
		private System.Nullable<System.DateTime> _NgayBatDau;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private EntityRef<tblCHUCVU> _tblCHUCVU;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnMaChucVuChanging(int value);
    partial void OnMaChucVuChanged();
    partial void OnLuongCoBanChanging(System.Nullable<decimal> value);
    partial void OnLuongCoBanChanged();
    partial void OnPhuCapChucVuChanging(System.Nullable<double> value);
    partial void OnPhuCapChucVuChanged();
    partial void OnNgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucChanged();
    #endregion
		
		public tblCHITIETCHUCVU()
		{
			this._tblCHUCVU = default(EntityRef<tblCHUCVU>);
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					if (this._tblCHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCoBan", DbType="Money")]
		public System.Nullable<decimal> LuongCoBan
		{
			get
			{
				return this._LuongCoBan;
			}
			set
			{
				if ((this._LuongCoBan != value))
				{
					this.OnLuongCoBanChanging(value);
					this.SendPropertyChanging();
					this._LuongCoBan = value;
					this.SendPropertyChanged("LuongCoBan");
					this.OnLuongCoBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCapChucVu", DbType="Float")]
		public System.Nullable<double> PhuCapChucVu
		{
			get
			{
				return this._PhuCapChucVu;
			}
			set
			{
				if ((this._PhuCapChucVu != value))
				{
					this.OnPhuCapChucVuChanging(value);
					this.SendPropertyChanging();
					this._PhuCapChucVu = value;
					this.SendPropertyChanged("PhuCapChucVu");
					this.OnPhuCapChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCHUCVU_tblCHITIETCHUCVU", Storage="_tblCHUCVU", ThisKey="MaChucVu", OtherKey="MaChucVu", IsForeignKey=true)]
		public tblCHUCVU tblCHUCVU
		{
			get
			{
				return this._tblCHUCVU.Entity;
			}
			set
			{
				tblCHUCVU previousValue = this._tblCHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._tblCHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCHUCVU.Entity = null;
						previousValue.tblCHITIETCHUCVUs.Remove(this);
					}
					this._tblCHUCVU.Entity = value;
					if ((value != null))
					{
						value.tblCHITIETCHUCVUs.Add(this);
						this._MaChucVu = value.MaChucVu;
					}
					else
					{
						this._MaChucVu = default(int);
					}
					this.SendPropertyChanged("tblCHUCVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblCHITIETCHUCVU", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblCHITIETCHUCVUs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblCHITIETCHUCVUs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCHUCVU")]
	public partial class tblCHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChucVu;
		
		private string _TenChucVu;
		
		private EntitySet<tblCHITIETCHUCVU> _tblCHITIETCHUCVUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChucVuChanging(int value);
    partial void OnMaChucVuChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    #endregion
		
		public tblCHUCVU()
		{
			this._tblCHITIETCHUCVUs = new EntitySet<tblCHITIETCHUCVU>(new Action<tblCHITIETCHUCVU>(this.attach_tblCHITIETCHUCVUs), new Action<tblCHITIETCHUCVU>(this.detach_tblCHITIETCHUCVUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCHUCVU_tblCHITIETCHUCVU", Storage="_tblCHITIETCHUCVUs", ThisKey="MaChucVu", OtherKey="MaChucVu")]
		public EntitySet<tblCHITIETCHUCVU> tblCHITIETCHUCVUs
		{
			get
			{
				return this._tblCHITIETCHUCVUs;
			}
			set
			{
				this._tblCHITIETCHUCVUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCHITIETCHUCVUs(tblCHITIETCHUCVU entity)
		{
			this.SendPropertyChanging();
			entity.tblCHUCVU = this;
		}
		
		private void detach_tblCHITIETCHUCVUs(tblCHITIETCHUCVU entity)
		{
			this.SendPropertyChanging();
			entity.tblCHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHOPDONG")]
	public partial class tblHOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHopDong;
		
		private string _LoaiHopDong;
		
		private System.Nullable<int> _ThoiHanHopDong;
		
		private EntitySet<tblNHANVIEN> _tblNHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(int value);
    partial void OnMaHopDongChanged();
    partial void OnLoaiHopDongChanging(string value);
    partial void OnLoaiHopDongChanged();
    partial void OnThoiHanHopDongChanging(System.Nullable<int> value);
    partial void OnThoiHanHopDongChanged();
    #endregion
		
		public tblHOPDONG()
		{
			this._tblNHANVIENs = new EntitySet<tblNHANVIEN>(new Action<tblNHANVIEN>(this.attach_tblNHANVIENs), new Action<tblNHANVIEN>(this.detach_tblNHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHopDong", DbType="NVarChar(50)")]
		public string LoaiHopDong
		{
			get
			{
				return this._LoaiHopDong;
			}
			set
			{
				if ((this._LoaiHopDong != value))
				{
					this.OnLoaiHopDongChanging(value);
					this.SendPropertyChanging();
					this._LoaiHopDong = value;
					this.SendPropertyChanged("LoaiHopDong");
					this.OnLoaiHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHanHopDong", DbType="Int")]
		public System.Nullable<int> ThoiHanHopDong
		{
			get
			{
				return this._ThoiHanHopDong;
			}
			set
			{
				if ((this._ThoiHanHopDong != value))
				{
					this.OnThoiHanHopDongChanging(value);
					this.SendPropertyChanging();
					this._ThoiHanHopDong = value;
					this.SendPropertyChanged("ThoiHanHopDong");
					this.OnThoiHanHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHOPDONG_tblNHANVIEN", Storage="_tblNHANVIENs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<tblNHANVIEN> tblNHANVIENs
		{
			get
			{
				return this._tblNHANVIENs;
			}
			set
			{
				this._tblNHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNHANVIENs(tblNHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblHOPDONG = this;
		}
		
		private void detach_tblNHANVIENs(tblNHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblHOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKHENTHUONGKYLUAT")]
	public partial class tblKHENTHUONGKYLUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKTKL;
		
		private int _MaNhanVien;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _Loai;
		
		private string _GhiChu;
		
		private System.Nullable<decimal> _Tien;
		
		private string _TrinhTrang;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKTKLChanging(int value);
    partial void OnMaKTKLChanged();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTienChanging(System.Nullable<decimal> value);
    partial void OnTienChanged();
    partial void OnTrinhTrangChanging(string value);
    partial void OnTrinhTrangChanged();
    #endregion
		
		public tblKHENTHUONGKYLUAT()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKTKL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKTKL
		{
			get
			{
				return this._MaKTKL;
			}
			set
			{
				if ((this._MaKTKL != value))
				{
					this.OnMaKTKLChanging(value);
					this.SendPropertyChanging();
					this._MaKTKL = value;
					this.SendPropertyChanged("MaKTKL");
					this.OnMaKTKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL")]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(30)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Money")]
		public System.Nullable<decimal> Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this.OnTienChanging(value);
					this.SendPropertyChanging();
					this._Tien = value;
					this.SendPropertyChanged("Tien");
					this.OnTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhTrang", DbType="NVarChar(30)")]
		public string TrinhTrang
		{
			get
			{
				return this._TrinhTrang;
			}
			set
			{
				if ((this._TrinhTrang != value))
				{
					this.OnTrinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TrinhTrang = value;
					this.SendPropertyChanged("TrinhTrang");
					this.OnTrinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblKHENTHUONGKYLUAT", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblKHENTHUONGKYLUATs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblKHENTHUONGKYLUATs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLUONG")]
	public partial class tblLUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLuong;
		
		private int _MaNhanVien;
		
		private System.Nullable<decimal> _TienLuong;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<int> _MaNhanVienLap;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLuongChanging(int value);
    partial void OnMaLuongChanged();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnTienLuongChanging(System.Nullable<decimal> value);
    partial void OnTienLuongChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnMaNhanVienLapChanging(System.Nullable<int> value);
    partial void OnMaNhanVienLapChanged();
    #endregion
		
		public tblLUONG()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLuong
		{
			get
			{
				return this._MaLuong;
			}
			set
			{
				if ((this._MaLuong != value))
				{
					this.OnMaLuongChanging(value);
					this.SendPropertyChanging();
					this._MaLuong = value;
					this.SendPropertyChanged("MaLuong");
					this.OnMaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL")]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienLuong", DbType="Money")]
		public System.Nullable<decimal> TienLuong
		{
			get
			{
				return this._TienLuong;
			}
			set
			{
				if ((this._TienLuong != value))
				{
					this.OnTienLuongChanging(value);
					this.SendPropertyChanging();
					this._TienLuong = value;
					this.SendPropertyChanged("TienLuong");
					this.OnTienLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVienLap", DbType="Int")]
		public System.Nullable<int> MaNhanVienLap
		{
			get
			{
				return this._MaNhanVienLap;
			}
			set
			{
				if ((this._MaNhanVienLap != value))
				{
					this.OnMaNhanVienLapChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVienLap = value;
					this.SendPropertyChanged("MaNhanVienLap");
					this.OnMaNhanVienLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblLUONG", Storage="_tblNHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblLUONGs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblLUONGs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNHANVIEN")]
	public partial class tblNHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _TenNhanVien;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _Email;
		
		private string _CMND;
		
		private string _DanToc;
		
		private string _TrinhDoHocVan;
		
		private string _TrinhTrangHonNhan;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private System.Nullable<double> _HeSoLuong;
		
		private string _Anh;
		
		private System.Nullable<int> _MaHopDong;
		
		private System.Nullable<int> _MaPhong;
		
		private EntitySet<tblBAOHIEM> _tblBAOHIEMs;
		
		private EntitySet<tblTAIKHOAN> _tblTAIKHOANs;
		
		private EntitySet<tblCHAMCONG> _tblCHAMCONGs;
		
		private EntitySet<tblCHITIETCHUCVU> _tblCHITIETCHUCVUs;
		
		private EntitySet<tblKHENTHUONGKYLUAT> _tblKHENTHUONGKYLUATs;
		
		private EntitySet<tblLUONG> _tblLUONGs;
		
		private EntityRef<tblHOPDONG> _tblHOPDONG;
		
		private EntityRef<tblPHONGBAN> _tblPHONGBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTrinhDoHocVanChanging(string value);
    partial void OnTrinhDoHocVanChanged();
    partial void OnTrinhTrangHonNhanChanging(string value);
    partial void OnTrinhTrangHonNhanChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    partial void OnHeSoLuongChanging(System.Nullable<double> value);
    partial void OnHeSoLuongChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnMaHopDongChanging(System.Nullable<int> value);
    partial void OnMaHopDongChanged();
    partial void OnMaPhongChanging(System.Nullable<int> value);
    partial void OnMaPhongChanged();
    #endregion
		
		public tblNHANVIEN()
		{
			this._tblBAOHIEMs = new EntitySet<tblBAOHIEM>(new Action<tblBAOHIEM>(this.attach_tblBAOHIEMs), new Action<tblBAOHIEM>(this.detach_tblBAOHIEMs));
			this._tblTAIKHOANs = new EntitySet<tblTAIKHOAN>(new Action<tblTAIKHOAN>(this.attach_tblTAIKHOANs), new Action<tblTAIKHOAN>(this.detach_tblTAIKHOANs));
			this._tblCHAMCONGs = new EntitySet<tblCHAMCONG>(new Action<tblCHAMCONG>(this.attach_tblCHAMCONGs), new Action<tblCHAMCONG>(this.detach_tblCHAMCONGs));
			this._tblCHITIETCHUCVUs = new EntitySet<tblCHITIETCHUCVU>(new Action<tblCHITIETCHUCVU>(this.attach_tblCHITIETCHUCVUs), new Action<tblCHITIETCHUCVU>(this.detach_tblCHITIETCHUCVUs));
			this._tblKHENTHUONGKYLUATs = new EntitySet<tblKHENTHUONGKYLUAT>(new Action<tblKHENTHUONGKYLUAT>(this.attach_tblKHENTHUONGKYLUATs), new Action<tblKHENTHUONGKYLUAT>(this.detach_tblKHENTHUONGKYLUATs));
			this._tblLUONGs = new EntitySet<tblLUONG>(new Action<tblLUONG>(this.attach_tblLUONGs), new Action<tblLUONG>(this.detach_tblLUONGs));
			this._tblHOPDONG = default(EntityRef<tblHOPDONG>);
			this._tblPHONGBAN = default(EntityRef<tblPHONGBAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(15)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(13)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(13)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(30)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoHocVan", DbType="NVarChar(30)")]
		public string TrinhDoHocVan
		{
			get
			{
				return this._TrinhDoHocVan;
			}
			set
			{
				if ((this._TrinhDoHocVan != value))
				{
					this.OnTrinhDoHocVanChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoHocVan = value;
					this.SendPropertyChanged("TrinhDoHocVan");
					this.OnTrinhDoHocVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhTrangHonNhan", DbType="NVarChar(30)")]
		public string TrinhTrangHonNhan
		{
			get
			{
				return this._TrinhTrangHonNhan;
			}
			set
			{
				if ((this._TrinhTrangHonNhan != value))
				{
					this.OnTrinhTrangHonNhanChanging(value);
					this.SendPropertyChanging();
					this._TrinhTrangHonNhan = value;
					this.SendPropertyChanged("TrinhTrangHonNhan");
					this.OnTrinhTrangHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuong", DbType="Float")]
		public System.Nullable<double> HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(MAX)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="Int")]
		public System.Nullable<int> MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._tblHOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Int")]
		public System.Nullable<int> MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._tblPHONGBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblBAOHIEM", Storage="_tblBAOHIEMs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblBAOHIEM> tblBAOHIEMs
		{
			get
			{
				return this._tblBAOHIEMs;
			}
			set
			{
				this._tblBAOHIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblTAIKHOAN", Storage="_tblTAIKHOANs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblTAIKHOAN> tblTAIKHOANs
		{
			get
			{
				return this._tblTAIKHOANs;
			}
			set
			{
				this._tblTAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblCHAMCONG", Storage="_tblCHAMCONGs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblCHAMCONG> tblCHAMCONGs
		{
			get
			{
				return this._tblCHAMCONGs;
			}
			set
			{
				this._tblCHAMCONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblCHITIETCHUCVU", Storage="_tblCHITIETCHUCVUs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblCHITIETCHUCVU> tblCHITIETCHUCVUs
		{
			get
			{
				return this._tblCHITIETCHUCVUs;
			}
			set
			{
				this._tblCHITIETCHUCVUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblKHENTHUONGKYLUAT", Storage="_tblKHENTHUONGKYLUATs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblKHENTHUONGKYLUAT> tblKHENTHUONGKYLUATs
		{
			get
			{
				return this._tblKHENTHUONGKYLUATs;
			}
			set
			{
				this._tblKHENTHUONGKYLUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblLUONG", Storage="_tblLUONGs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<tblLUONG> tblLUONGs
		{
			get
			{
				return this._tblLUONGs;
			}
			set
			{
				this._tblLUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHOPDONG_tblNHANVIEN", Storage="_tblHOPDONG", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public tblHOPDONG tblHOPDONG
		{
			get
			{
				return this._tblHOPDONG.Entity;
			}
			set
			{
				tblHOPDONG previousValue = this._tblHOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._tblHOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHOPDONG.Entity = null;
						previousValue.tblNHANVIENs.Remove(this);
					}
					this._tblHOPDONG.Entity = value;
					if ((value != null))
					{
						value.tblNHANVIENs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHOPDONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPHONGBAN_tblNHANVIEN", Storage="_tblPHONGBAN", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public tblPHONGBAN tblPHONGBAN
		{
			get
			{
				return this._tblPHONGBAN.Entity;
			}
			set
			{
				tblPHONGBAN previousValue = this._tblPHONGBAN.Entity;
				if (((previousValue != value) 
							|| (this._tblPHONGBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPHONGBAN.Entity = null;
						previousValue.tblNHANVIENs.Remove(this);
					}
					this._tblPHONGBAN.Entity = value;
					if ((value != null))
					{
						value.tblNHANVIENs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblPHONGBAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBAOHIEMs(tblBAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblBAOHIEMs(tblBAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblTAIKHOANs(tblTAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblTAIKHOANs(tblTAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblCHAMCONGs(tblCHAMCONG entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblCHAMCONGs(tblCHAMCONG entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblCHITIETCHUCVUs(tblCHITIETCHUCVU entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblCHITIETCHUCVUs(tblCHITIETCHUCVU entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblKHENTHUONGKYLUATs(tblKHENTHUONGKYLUAT entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblKHENTHUONGKYLUATs(tblKHENTHUONGKYLUAT entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblLUONGs(tblLUONG entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblLUONGs(tblLUONG entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPHONGBAN")]
	public partial class tblPHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private string _TenPhong;
		
		private string _GhiChu;
		
		private EntitySet<tblNHANVIEN> _tblNHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblPHONGBAN()
		{
			this._tblNHANVIENs = new EntitySet<tblNHANVIEN>(new Action<tblNHANVIEN>(this.attach_tblNHANVIENs), new Action<tblNHANVIEN>(this.detach_tblNHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPHONGBAN_tblNHANVIEN", Storage="_tblNHANVIENs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<tblNHANVIEN> tblNHANVIENs
		{
			get
			{
				return this._tblNHANVIENs;
			}
			set
			{
				this._tblNHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNHANVIENs(tblNHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblPHONGBAN = this;
		}
		
		private void detach_tblNHANVIENs(tblNHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblPHONGBAN = null;
		}
	}
}
#pragma warning restore 1591
